export const sampleManagementButtons = [
  "Collection Pending",
  "Sample Collected",
  "Dept. Rec. Pending",
  "Dept Received",
  "Urgent",
  "Rejected",
  "SNR",
];

export const SampleManagementTableHeader = [
  "#",
  "Lab No",
  "Bill Date",
  "UHID",
  "Patient Name",
  "Age/Gender",
  "Client Name",
  "",
  "Investigation",
  "Sample Type",
  "Color",
  "BarCode",
  "Sample Collection",
  "Dept. Rec.",
  "Reject",
  "Remark",
  "",
  "Stickers",
  "Info",
];

export const PatientInvestigationTableHeader = [
  "#",
  "Investigation Name",
  "Bill Date",
  "Billing By",
  "Collection Date",
  "Collected By",
  "Received Date",
  "Received By",
  "Rejected Date",
  "Rejected By",
  "Sample Rejected Reason",
  "Result Entered Date",
  "Result Entered By",
  "Approved Date",
  "Approved By",
];

export const LabResultEntryButtons = [
  "Result Pending",
  "Hold",
  "Report Approved Pending",
  "Approved",
  "Printed",
  "Dispatched",
  "ReRun",
];
export const LabResultEntryTableHeader = [
  "#",
  "Lab No",
  "Bill Date",
  "UHID",
  "Patient Name",
  "Age/Gender",
  "Client Name",
  "Due Amount",
  "",
  "",
  "",
  "Investigation",
  "BarCode",
  "Delivery Date",
  "Print",
  "Approve",
  "Approved Date",
  "Remark",
  "Info",
];

export const LREPatientInvestigationTableHeader = [
  "#",
  "Investigation Name",
  "Bill Date",
  "Billing By",
  "Test Remark",
  "Collection Date",
  "Collected By",
  "Received Date",
  "Received By",
  "Rejected Date",
  "Rejected By",
  "Sample Rejected Reason",
  "Result Entered Date",
  "Result Entered By",
  "Approved Date",
  "Approved By",
];

export const LRPatientRemarkTableHeader = [
  "#",
  "Sample Remark",
  "Remark",
  "Remark Date",
  "Create By",
  "Is Internal",
  "Edit",
  "Delete",
];
