export const formConfig = [
  { type: "heading", label: "Create New User", color: "black" },
  { type: "reuiredErrorMessage", label: "Fields marked with * are required" },
  {
    type: "text",
    label: "First Name",
    fieldId: "textFirstName",
    required: true,
    validation: "^[a-zA-Z]+$",
    minLength: 6,
    maxLength: 10,
  },
  {
    type: "text",
    label: "Middle Name",
    fieldId: "textMiddleName",
    validation: "^[a-zA-Z]+$",
    required: false,
  },
  {
    type: "text",
    label: "Last Name",
    fieldId: "textLastName",
    validation: "^[a-zA-Z]+$",
    required: false,
  },
  {
    type: "select",
    label: "Gender",
    fieldId: "pickGender",
    required: true,
  },
  {
    type: "date",
    label: "Date of Birth",
    fieldId: "dobText",
    required: true,
    minDate: "1900-01-01",
    maxDate: new Date().toISOString().split("T")[0],
  },
  {
    type: "email",
    label: "Email",
    fieldId: "textEmail",
    required: true,
    validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
  },
  {
    type: "text",
    label: "Contact Number",
    fieldId: "textContact",
    required: true,
    validation: "^[0-9]{10}$",
    minLength: 10,
    maxLength: 10,
  },
  {
    type: "textArea",
    label: "Address",
    fieldId: "textAddress",
    required: false,
    maxLength: 500,
  },
  {
    type: "text",
    label: "User Name",
    fieldId: "textUserName",
    required: true,
    validation: "^[a-zA-Z]+$",
    minLength: 4,
    maxLength: 15,
  },
  {
    type: "password",
    label: "Password",
    fieldId: "txtPassword",
    required: true,
    validation: "^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.{6,15}$)",
    minLength: 6,
    maxLength: 15,
  },
  {
    type: "password",
    label: "Confirm Password",
    fieldId: "textConfirmPassword",
    required: true,
    validation: "^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.{6,15}$)",
  },
  {
    type: "text",
    label: "User Department ID",
    fieldId: "textUserDepartmentId",
    required: false,
    validation: "^[a-zA-Z]+$",
  },
  {
    type: "button",
    label: "Submit",
    action: "handleSubmitButton",
  },
  // {
  //   type: "buttonGroup",
  //   buttons: [
  //     {
  //       type: "button",
  //       label: "Edit",
  //     },
  //     {
  //       type: "button",
  //       label: "Submit",
  //     },
  //   ],
  // },
];
