import { IMAGES } from "./index";

export const LOGOS = [
  { id: 1, label: "Accountant", value: IMAGES.Accountant },
  { id: 2, label: "Admin", value: IMAGES.AdminLogo },
  { id: 3, label: "Anesthesia", value: IMAGES.Anesthesia },
  { id: 4, label: "Avatar", value: IMAGES.Avatar },
  { id: 5, label: "Blood Bank", value: IMAGES.BloodBank },
  { id: 6, label: "Camp", value: IMAGES.Camp },
  { id: 7, label: "Cardiology", value: IMAGES.Cardiology },
  { id: 8, label: "CT Scan", value: IMAGES.CtScan },
  { id: 9, label: "Day Care", value: IMAGES.DayCare },
  { id: 10, label: "Dialysis", value: IMAGES.Dialysis },
  { id: 11, label: "Expense Management", value: IMAGES.ExpenseManagement },
  { id: 12, label: "Front Office", value: IMAGES.FrontOffice },
  { id: 13, label: "General Store", value: IMAGES.GeneralStore },
  { id: 14, label: "Human Resources", value: IMAGES.HumanResources },
  { id: 15, label: "IPD", value: IMAGES.IPD },
  { id: 16, label: "Lab", value: IMAGES.Lab },
  { id: 17, label: "Medical Equipment", value: IMAGES.MedicalEquipment },
  { id: 18, label: "Medical Store", value: IMAGES.MedicalStore },
  { id: 19, label: "Pharmacy", value: IMAGES.Pharmacy },
  { id: 20, label: "Quality Control", value: IMAGES.QualityControl },
  { id: 21, label: "Radiology", value: IMAGES.Radiology },
  { id: 22, label: "Vaccine", value: IMAGES.Vaccine },
  { id: 23, label: "Transport", value: IMAGES.Transport },
  { id: 24, label: "Emergency", value: IMAGES.Emergency },
  { id: 25, label: "NursingWard", value: IMAGES.NursingWard },
  { id: 26, label: "OT", value: IMAGES.OT },
];
